#!/bin/bash
# Use https://www.shellcheck.net/ to reduce mistakes if you make changes to this file.
# Retrieved from https://raw.githubusercontent.com/dask/helm-chart/master/ci/common

# Awaits deployments, statefulsets, and daemonsets becoming ready.
full_namespace_await() {
    kubectl get deploy,sts,ds -o name \
    | xargs --max-args 1 --no-run-if-empty \
    kubectl rollout status --timeout=3m
}