---
nameOverride: ooi-data-harvester
fullnameOverride: ooi-data-harvester

agent:
  enabled: true
  replicas: 1
  image:
    repository: prefecthq/prefect
    tag: latest
    pullSecrets: []
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
  env:
  - name: PREFECT__CLOUD__AGENT__AUTH_TOKEN
    value: ""
  - name: PREFECT__CLOUD__AUTH_TOKEN
    value: ""
  - name: PREFECT__CLOUD__API
    value: "https://api.prefect.io"
  - name: NAMESPACE
    value: "default"
  - name: IMAGE_PULL_SECRETS
    value: ""
  - name: PREFECT__CLOUD__AGENT__LABELS
    value: "[]"
  # A path to where the YAML template should be loaded from
  # This yaml template should be in the Docker image of agent!
  # - name: YAML_TEMPLATE
  #   value: ""
  - name: JOB_MEM_REQUEST
    value: ""
  - name: JOB_MEM_LIMIT
    value: ""
  - name: JOB_CPU_REQUEST
    value: ""
  - name: JOB_CPU_LIMIT
    value: ""
  - name: IMAGE_PULL_POLICY
    value: ""
  - name: SERVICE_ACCOUNT_NAME
    value: ""
  - name: PREFECT__BACKEND
    value: "cloud"
  - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
    value: "http://:8080"