agent:
    enabled: true
    env:
    - name: PREFECT__CLOUD__AGENT__AUTH_TOKEN
      valueFrom:
        secretKeyRef:
        name: cava-secrets
        key: prefect-cloud-agent-token
    - name: PREFECT__CLOUD__AUTH_TOKEN
      valueFrom:
        secretKeyRef:
        name: cava-secrets
        key: prefect-cloud-token
    - name: PREFECT__CLOUD__API
      value: https://api.prefect.io
    - name: PREFECT__CLOUD__AGENT__LABELS
      value: "[]"
    - name: JOB_MEM_REQUEST
      value: ''
    - name: JOB_MEM_LIMIT
      value: ''
    - name: JOB_CPU_REQUEST
      value: ''
    - name: JOB_CPU_LIMIT
      value: ''
    - name: IMAGE_PULL_POLICY
      value: ''
    - name: SERVICE_ACCOUNT_NAME
      value: ''
    - name: YAML_TEMPLATE
      value: '/opt/agent_job_spec.yml'
    - name: PREFECT__BACKEND
      value: cloud
    - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
      value: http://:8080