name: Test Harvester Chart

on:
  push:
    paths: ["ooi-data-harvester/**", "**/test-chart.yml", ".ci-helpers/common"]
  pull_request:
    paths: ["ooi-data-harvester/**", "**/test-chart.yml", ".ci-helpers/common"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        # We run this job multiple times with different parameterization
        # specified below, these parameters have no meaning on their own and
        # gain meaning on how job steps use them.
        #
        # k3s-version: https://github.com/rancher/k3s/tags
        # k3s-channel: https://update.k3s.io/v1-release/channels
        include:
          - k3s-channel: v1.19
          - k3s-channel: v1.16

    steps:
      - uses: actions/checkout@v2
      - name: Install helm
        run: |
          curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get-helm-3 | bash

      - name: Lint chart's templates
        run: |
          helm lint ./ooi-data-harvester --strict --values ooi-data-harvester/dev-values.yaml

      - name: Validate chart's templates can render
        run: |
          helm template ./ooi-data-harvester --values ooi-data-harvester/dev-values.yaml 1>/dev/null

      # Starts a k8s cluster with NetworkPolicy enforcement and installs kubectl
      #
      # ref: https://github.com/manics/action-k3s-helm/
      - uses: manics/action-k3s-helm@v1
        with:
          k3s-channel: ${{ matrix.k3s-channel }}
          metrics-enabled: false
          traefik-enabled: false
          docker-enabled: false

      - name: Validate charts' rendered templates are valid k8s resources
        run: |
          helm template ./ooi-data-harvester --validate --values ooi-data-harvester/dev-values.yaml 1>/dev/null

      - name: Install chart and await readiness
        run: |
          helm install ooi-data-harvester ./ooi-data-harvester --values ooi-data-harvester/dev-values.yaml

          . .ci-helpers/common
          full_namespace_await

      # GitHub Action reference: https://github.com/jupyterhub/action-k8s-namespace-report
      - name: Kubernetes namespace report
        uses: jupyterhub/action-k8s-namespace-report@v1
        if: always()
